Modified comments in 4_switch_controlled_motor_normal
SRA-VJTI/Wall-E pull request #123
Opened 2023-01-15 10:41 UTC by PritK99

Modified comments in 4_switch_controlled_motor_normal

2023-01-16 12:23 UTC, Jamm02 commented
@RISHI27-dot please review the PR

2023-01-18 04:54 UTC, RISHI27-dot requested changes

2023-01-18 04:54 UTC, RISHI27-dot commented on 4_switch_controlled_motor_normal/main/switch_control_motor_normal.c
> +			// if neither of switch 3 or switch 4 is pressed on then stop the motor A_1
Change to "  if neither of switch 3 or switch 4 is pressed, stop the motor A_1. "

2023-01-18 04:54 UTC, RISHI27-dot commented on 4_switch_controlled_motor_normal/main/switch_control_motor_normal.c
> +			// if neither of switch 1 or switch 2 is pressed on then stop the motor A_0
Change to " if neither of switch 1 or switch 2 is pressed, stop the motor A_0. "

2023-01-18 04:54 UTC, RISHI27-dot commented on 4_switch_controlled_motor_normal/README.md
> +    The following flowchart represents the flow of code
Change to " The code flow is illustrated in the flowchart below. "

2023-01-18 04:54 UTC, RISHI27-dot commented on 4_switch_controlled_motor_normal/README.md
> +    - runs the bot motors in Normal mode and controls the motors according to the switches activated.
runs -> Runs.
Normal -> normal

2023-03-27 14:05 UTC, closed without merging