Edited Documentation for LSA
SRA-VJTI/Wall-E pull request #128
Opened 2023-01-16 18:44 UTC by ChinmayMundane

This pull request solves the following issue:
1) Removed the Acknowledgement Tag from Readme.
2) Changed Images from old LSA to current version.
3) Changed the LSA content from the table

2023-01-19 03:31 UTC, ChinmayLonkar commented on 2_LSA/README.md
> +<img src="assets/LSA_physical.jpeg" width="800" height="450">
Add a better-quality image in png format.

2023-01-19 03:32 UTC, ChinmayLonkar commented on 2_LSA/README.md
> +<img src="assets/LSA.png" width="800" height="400">
use the screenshot of the updated LSA PCB in KiCAD

2023-01-19 03:35 UTC, ChinmayLonkar commented on 2_LSA/README.md
> +| LED         | Emits light   |  5       |
Make it IR LED and Phototransistor.

2023-01-19 03:43 UTC, ChinmayLonkar requested changes
Update the `Function of Components` section as per the current LSA :))

2024-02-01 18:40 UTC, SuperChamp234 commented
Closing this PR as it is stale.

2024-02-01 18:40 UTC, closed without merging